### ISSUE TITLE
Condition form input

### ISSUE THREAD

**Issue by jburton6** [mstudar1/clinic#17]
We want strings of data to be consistent in the DB:
- [x] Want SSN to be 555-55-5555
- [x] Want phone numbers to be (555)555-5555
- [x] Want gender to be single letter?
- [x] Want states to be postal abbreviations
- [x] Want cities to have capital first letter
- [x] Want zips to be just 5 digits? (no extra four)
- [x] Want names to start with capital but rest lowercase

**Comment by mstudar1** [comment]
I added some crude input validation to the Person class.  The view will need to catch any ArgumentExceptions that are thrown when setting properties.  Each ArgumentException's message contains instructions with how to format the input properly; this can be displayed to the user.

I noticed that not all of the seed data in the database complies with the specifications listed above.  We might want to think about updating this for testing purposes.

Here are a few notes about the specific regular expressions:
- For phone numbers, I included a mandatory space between the area code and the prefix.
- For states, it just looks for two capital letters (it doesn't check to make sure it is a valid state).  We could consider using a combo box on the forms in the future.
- For names, I enforced a mandatory capital letter at the beginning, but I didn't do anything else.  The reason I didn't enforce lowercase letters after the first character is because that might not be the case for some names (e.g., McIntyre).  So the current input validation has some gaps (e.g., it allows numeric characters after the first letter).

Since the merge that I just added isn't bulletproof, I am leaving this issue open.  Time permitting, we might be able to come back and clean up the regular expressions.  Each type of property has a helper method at the end of the class for validating.  It should be as simple as changing the regex to change the requirements.

**Comment by jburton6** [comment]
I think the phone number one might need some work.  I ran into a problem that seemed to trace to the validator.  I didn't have time to tinker too much so I just commented it out in my local copy and got my stuff working.  In troubleshooting, I did fix all the numbers in my local DB.  I'll generate a new script tomorrow to distribute.

**Comment by jburton6** [comment]
Fixed the issue.  It was caused by two things: 
1 - In the DAL the select parameter was limiting to 10 char when the DB holds 20 (includes dashes and spaces)
2 - Added trim to local variable in model validation method to remove white space before test

**Comment by jburton6** [comment]
I like your idea about changing SSN and Phone fields in the DB to just hold numbers (still strings though).  The validation would then just need to strip other characters from the input and make sure the correct number of digits are present.  We could easily use the following:
string cleanedValue = Regex.Replace(rawValue, "[^.0-9]", "");

We just need a plan for doing this without stepping on each other while working on files.  Here are the files and tasks that I think would be involved:
- [ ] Person model file - adjust the validator statements to simply clean the data and throw exceptions when not possible or wrong number of digits.
- [ ] Files that display SSN or Phone need to add code to take the raw value from DB and make it pretty.  I think this will involve a lot of files.  Might need to pick a window of time when one of us can do this on fully update master branch with the others staying out of the way.

**Comment by jburton6** [comment]
Feature that might be nice if we have time, but I'm closing this as it is not essential
