### ISSUE TITLE
Patients Tab

### ISSUE THREAD

**Issue by jburton6** [mstudar1/clinic#71]
- [x] clicking on appointments of a selected patient, it shows the appointment tab. The search result header after DOB doesn’t make sense

**Comment by mstudar1** [comment]
I'm assuming that the issue here was that if you enter a last name on the appointments tab, then click on an appointment button for a different patient on the patients tab, the list of appointments does not apply for the last name shown in the search box.  I added code to clear the last name search box in this situation.  I also reset the date inputs to today's date (which is what they default to when the form is first launched).  Finally, I changed the label text from "search results" to "appointments".
